// vue/src/app/components/App.vue
<template>
  <div id="app">
    <section class="todoapp">
      <header class="header">
        <h1 style="color:seagreen">Todos</h1>
        <img src="src/assets/images/vue-logo.png" height="100" width="100" style="position:absolute;top:-109px;margin-left: 40px">
        <input class="new-todo" autofocus autocomplete="off" placeholder="What needs to be done?" v-model="newTodo" @keyup.enter="addTodo">
      </header>
      <section class="main" v-show="todos.length" v-cloak>
        <input class="toggle-all" type="checkbox" v-model="allDone">
        <ul class="todo-list">
          <li v-for="todo in filteredTodos" class="todo" :key="todo.id" :class="{ completed: todo.completed, editing: todo == editedTodo }">
            <div class="view">
              <input class="toggle" type="checkbox" v-model="todo.completed">
              <label @dblclick="editTodo(todo)">{{ todo.title }}</label>
              <button class="destroy" @click="removeTodo(todo)"></button>
            </div>
            <input class="edit" type="text" v-model="todo.title" v-todo-focus="todo == editedTodo" @blur="doneEdit(todo)" @keyup.enter="doneEdit(todo)"
              @keyup.esc="cancelEdit(todo)">
          </li>
        </ul>
      </section>
      <footer class="footer" v-show="todos.length" v-cloak>
        <span class="todo-count">
          <strong>{{ remaining }}</strong> {{ remaining | pluralize }} left
        </span>
        <ul class="filters">
          <li><a href="/all" :class="{ selected: visibility == 'all' }">All</a></li>
          <li><a href="/active" :class="{ selected: visibility == 'active' }">Active</a></li>
          <li><a href="/completed" :class="{ selected: visibility == 'completed' }">Completed</a></li>
        </ul>
        <button class="clear-completed" @click="removeCompleted" v-show="todos.length > remaining">
      Clear completed
    </button>
      </footer>
    </section>
    <footer class="info" style="font-size:larger">
      Double-click to edit a todo
    </footer>
  </div>
</template>

<script>
  // localStorage persistence
  var STORAGE_KEY = 'todos-vuejs-2.0'

  var todoStorage = {
    fetch: function() {
      var todos = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]')
      todos.forEach(function(todo, index) {
        todo.id = index
      })
      todoStorage.uid = todos.length
      return todos
    },
    save: function(todos) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(todos))
    }
  }

  // visibility filters
  var filters = {
    all: function(todos) {
      return todos
    },
    active: function(todos) {
      return todos.filter(function(todo) {
        return !todo.completed
      })
    },
    completed: function(todos) {
      return todos.filter(function(todo) {
        return todo.completed
      })
    }
  }

  var app = {
    name: 'app',
    created() {
      this.visibility = window.location.pathname.replace(/\//, '')
    },
    data() {
      return {
        todos: todoStorage.fetch(),
        newTodo: '',
        editedTodo: null,
        visibility: 'all'
      }
    },
    // watch todos change for localStorage persistence
    watch: {
      todos: {
        handler: function(todos) {
          todoStorage.save(todos)
        },
        deep: true
      },
      '$route'(to, from) {
        console.log(to, from);
      }
    },
    // computed properties
    computed: {
      filteredTodos: function() {
        return filters[this.visibility](this.todos)
      },
      remaining: function() {
        return filters.active(this.todos).length
      },
      allDone: {
        get: function() {
          return this.remaining === 0
        },
        set: function(value) {
          this.todos.forEach(function(todo) {
            todo.completed = value
          })
        }
      }
    },
    filters: {
      pluralize: function(n) {
        return n === 1 ? 'item' : 'items'
      }
    },
    // methods that implement data logic.
    // note there's no DOM manipulation here at all.
    methods: {
      addTodo: function() {
        var value = this.newTodo && this.newTodo.trim()
        if (!value) {
          return
        }
        this.todos.push({
          id: todoStorage.uid++,
          title: value,
          completed: false
        })
        this.newTodo = ''
      },
      removeTodo: function(todo) {
        this.todos.splice(this.todos.indexOf(todo), 1)
      },
      editTodo: function(todo) {
        this.beforeEditCache = todo.title
        this.editedTodo = todo
      },
      doneEdit: function(todo) {
        if (!this.editedTodo) {
          return
        }
        this.editedTodo = null
        todo.title = todo.title.trim()
        if (!todo.title) {
          this.removeTodo(todo)
        }
      },
      cancelEdit: function(todo) {
        this.editedTodo = null
        todo.title = this.beforeEditCache
      },
      removeCompleted: function() {
        this.todos = filters.active(this.todos)
      },
      show: function(v) {
        this.visibility = $route.params.id;
      }
    },
    directives: {
      'todo-focus': function(el, value) {
        if (value) {
          el.focus()
        }
      }
    }
  }

  export default app;

</script>

<style>

</style>

// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoStore, Todo } from './services/store';
import '../assets/css/styles.css';

@Component({
	selector: 'app',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css']
})

export class AppComponent implements OnInit {
	todoStore: TodoStore;
	newTodoText = '';
	visibility = 'all';

	ngOnInit() {
		let path = window.location.pathname.replace(/\//, '');
		this.visibility = path ? path : 'all'
	}
	constructor(todoStore: TodoStore) {
		this.todoStore = todoStore;
	}

	stopEditing(todo: Todo, editedTitle: string) {
		todo.title = editedTitle;
		todo.editing = false;
	}

	cancelEditingTodo(todo: Todo) {
		todo.editing = false;
	}

	updateEditingTodo(todo: Todo, editedTitle: string) {
		editedTitle = editedTitle.trim();
		todo.editing = false;

		if (editedTitle.length === 0) {
			return this.todoStore.remove(todo);
		}

		todo.title = editedTitle;
	}

	editTodo(todo: Todo) {
		todo.editing = true;
	}

	removeCompleted() {
		this.todoStore.removeCompleted();
	}

	toggleCompletion(todo: Todo) {
		this.todoStore.toggleCompletion(todo);
	}

	remove(todo: Todo) {
		this.todoStore.remove(todo);
	}

	addTodo() {
		if (this.newTodoText.trim().length) {
			this.todoStore.add(this.newTodoText);
			this.newTodoText = '';
		}
	}
}
<main>
  <section class="todoapp">
    <header class="header">
      <h1 style="color:crimson">Todos</h1>
      <img class="logo" src="../assets/images/angular-logo.png" height="120">
      <input class="new-todo" placeholder="What needs to be done?" autofocus [(ngModel)]="newTodoText" (keyup.enter)="addTodo()">
    </header>
    <section class="main" *ngIf="todoStore.todos.length > 0">
      <input class="toggle-all" type="checkbox" *ngIf="todoStore.todos.length" #toggleall [checked]="todoStore.allCompleted()"
        (click)="todoStore.setAllTo(toggleall.checked)">
      <ul class="todo-list">
        <li *ngFor="let todo of todoStore.todos" [class.completed]="todo.completed" [class.editing]="todo.editing">
          <div class="view">
            <input class="toggle" type="checkbox" (click)="toggleCompletion(todo)" [checked]="todo.completed">
            <label (dblclick)="editTodo(todo)">{{todo.title}}</label>
            <button class="destroy" (click)="remove(todo)"></button>
          </div>
          <input class="edit" *ngIf="todo.editing" [value]="todo.title" #editedtodo (blur)="stopEditing(todo, editedtodo.value)" (keyup.enter)="updateEditingTodo(todo, editedtodo.value)"
            (keyup.escape)="cancelEditingTodo(todo)">
        </li>
      </ul>
    </section>
    <footer class="footer" *ngIf="todoStore.todos.length > 0">
      <span class="todo-count"><strong>{{todoStore.getRemaining().length}}</strong> {{todoStore.getRemaining().length == 1 ? 'item' : 'items'}} left</span>
      <ul class="filters">
        <li><a href="/all" [class.selected]="visibility == 'all'">All</a></li>
        <li><a href="/active" [class.selected]="visibility == 'active'">Active</a></li>
        <li><a href="/completed" [class.selected]="visibility == 'completed'">Completed</a></li>
      </ul>
      <button class="clear-completed" *ngIf="todoStore.getCompleted().length > 0" (click)="removeCompleted()">Clear completed</button>
    </footer>
  </section>
  <footer class="info" style="font-size:larger">
    Double-click to edit a todo
  </footer>
</main>
